### ISSUE TITLE
windows Issues

### ISSUE THREAD

**Issue by ghost** [lux-lth/JobFinder#2]
Testé sur Windows : 
Nécessaire pour fonctionner :

- Création du fichier : already_sent.csv
````
Traceback (most recent call last):
  File "D:\Users\xxx\Desktop\JobFinder.py", line 220, in <module>
    jf.send_mails()
  File "D:\Users\xxx\Desktop\JobFinder.py", line 137, in send_mails
    with open('already_sent.csv') as f:
IOError: [Errno 2] No such file or directory: 'already_sent.csv'
````

- Modification les lignes :
````
103 =>                                 f.write(line.encode('utf-8')+"\n")      
131 =>            print('> Votre choix : ', end == "")
````

**Comment by lc-thomas** [comment]
Bien vu pour le already_sent.csv.
Quand à l'autre problème, c'est dû à la version de python utilisée. Cet outil est fait pour python3
